### ISSUE TITLE
Chinese text

### ISSUE THREAD

**Issue by ghost** [Verclene/LittleMaidReengaged#1]
请更新
Please update

> entity.lmreengaged.LittleMaidX.name=女仆酱
> 
> item.lmreengaged:spawn_littlemaid_egg.name=生成 女仆酱
> item.lmreengaged:registerkey.name=§e物品模式添加器
> item.lmreengaged:maidporter.name=女仆储存蛋
> 
> achievement.contract=签订契约了！ 我的主人
> achievement.contract.desc=捕获一只女仆
> 
> achievement.fencer=保护我们的主人！
> achievement.fencer.desc=开启剑客模式
> 
> achievement.bloodsucker=不可饶恕 @%%@&$_#&#_...
> achievement.bloodsucker.desc=开启嗜血模式
> 
> achievement.archer=敌人将无法逃脱
> achievement.archer.desc=开启弓箭模式
> 
> achievement.blazingstar=什么都无法靠近我 主人除外
> achievement.blazingstar.desc=开启嗜血弓箭模式
> 
> achievement.cooking=我是打铁高手!?
> achievement.cooking.desc=开启烧炼模式
> 
> achievement.farmer="能感觉到阵阵微风拂过大地吗？  光影MOD可以哦"
> achievement.farmer.desc=开启农场模式
> 
> achievement.healer=我们要让主人的状态满满♀的
> achievement.healer.desc=开启奶妈模式
> 
> achievement.pharmacist=邻苯二甲酸 混合 乙酸酐 等于什么呢？
> achievement.pharmacist.desc=开启酿造模式
> 
> achievement.ripper=开始绿化吧!
> achievement.ripper.desc=开启剪刀模式
> 
> achievement.torcher=主人  我怕鬼...
> achievement.torcher.desc=开启照明模式
> 
> achievement.zombuster=这是一个带有齿痕的铲子!
> achievement.zombuster.desc="拿着它开始挖吧!"
> 
> achievement.overprtct=过度的保护
> achievement.overprtct.desc="这身铠甲真难看."
> 
> achievement.ashikubi=哎呀。这伤害 :(
> achievement.ashikubi.desc="只是伤到了腿? 拜托,你都快死了."
> 
> achievement.boost=感觉好热!
> achievement.boost.desc="拿这个替代糖? ... 没门.
> 
> achievement.myfavorite=我最喜欢的东西
> achievement.myfavorite.desc="是那最甘甜的物品 ..."
> 
> littleMaidMob.mode.Torcher=照明模式
> littleMaidMob.mode.F-Torcher=自由-照明模式
> littleMaidMob.mode.T-Torcher=巡逻—照明模式)
> 
> littleMaidMob.mode.Archer=弓箭模式
> littleMaidMob.mode.F-Archer=自由-弓箭模式
> littleMaidMob.mode.T-Archer=巡逻-弓箭模式
> 
> littleMaidMob.mode.Blazingstar=嗜血弓箭模式
> littleMaidMob.mode.F-Blazingstar=自由-嗜血弓箭模式
> littleMaidMob.mode.T-Blazingstar=巡逻-嗜血弓箭模式
> 
> littleMaidMob.mode.Playing=玩耍模式
> littleMaidMob.mode.F-Playing=自由-玩耍模式
> littleMaidMob.mode.T-Playing=巡逻-玩耍模式
> 
> littleMaidMob.mode.Pharmacist=酿造模式
> littleMaidMob.mode.F-Pharmacist=自由-酿造模式
> littleMaidMob.mode.T-Pharmacist=巡逻-酿造模式
> 
> littleMaidMob.mode.Healer=奶妈模式
> littleMaidMob.mode.F-Healer=自由-奶妈模式
> littleMaidMob.mode.T-Healer=巡逻-奶妈模式
> 
> littleMaidMob.mode.Cooking=烧炼模式
> littleMaidMob.mode.F-Cooking=自由-烧炼模式
> littleMaidMob.mode.T-Cooking=巡逻-烧炼模式
> 
> littleMaidMob.mode.Strike=罢工
> littleMaidMob.mode.Wait=待命
> littleMaidMob.mode.Wild=野生
> 
> littleMaidMob.mode.Escorter=跟随模式
> littleMaidMob.mode.F-Escorter=自由模式
> littleMaidMob.mode.T-Escorter=巡逻模式
> 
> littleMaidMob.mode.Fencer=剑客模式
> littleMaidMob.mode.F-Fencer=自由-剑客模式
> littleMaidMob.mode.T-Fencer=巡逻-剑客模式
> 
> littleMaidMob.mode.Bloodsucker=嗜血模式
> littleMaidMob.mode.F-Bloodsucker=自由-嗜血模式
> littleMaidMob.mode.T-Bloodsucker=巡逻-嗜血模式
> 
> littleMaidMob.mode.Ripper=剪刀模式
> littleMaidMob.mode.F-Ripper=自由-剪刀模式
> littleMaidMob.mode.T-Ripper=巡逻-剪刀模式
> 
> littleMaidMob.mode.TNT-D=自爆模式
> littleMaidMob.mode.F-TNT-D=自由-自爆模式
> littleMaidMob.mode.T-TNT-D=巡逻-自爆模式
> 
> littleMaidMob.mode.Detonator=轰炸机模式
> littleMaidMob.mode.F-Detonator=自由-轰炸机模式
> littleMaidMob.mode.T-Detonator=巡逻-轰炸机模式
> 
> littleMaidMob.mode.Farmer=农场模式
> littleMaidMob.mode.F-Farmer=自由-农场模式
> littleMaidMob.mode.T-Farmer=巡逻-农场模式
> 
> littleMaidMob.mode.FarmPorter=搬运工模式(测试)
> littleMaidMob.mode.F-FarmPorter=自由-搬运工模式
> littleMaidMob.mode.T-FarmPorter=巡逻-搬运工模式
> 
> littleMaidMob.mode.DeathWait=致命伤
> littleMaidMob.mode.F-DeathWait=自由-致命伤
> littleMaidMob.mode.T-DeathWait=巡逻-致命伤
> 
> littleMaidMob.text.Health=健康值
> littleMaidMob.text.AP=护甲值
> littleMaidMob.text.STATUS=血量值
> 
> littleMaidMob.gui.toggle.inner.show=显示盔甲内侧材质
> littleMaidMob.gui.toggle.inner.hide=隐藏盔甲内侧材质
> littleMaidMob.gui.toggle.innerlight.show=显示盔甲内侧发光材质
> littleMaidMob.gui.toggle.innerlight.hide=隐藏盔甲内侧发光材质
> littleMaidMob.gui.toggle.outer.show=显示盔甲外侧材质
> littleMaidMob.gui.toggle.outer.hide=隐藏盔甲外侧材质
> littleMaidMob.gui.toggle.outerlight.show=显示盔甲外侧发光材质
> littleMaidMob.gui.toggle.outerlight.hide=隐藏盔甲外侧发光材质
> littleMaidMob.gui.toggle.swim.enable=启用游泳模式
> littleMaidMob.gui.toggle.swim.disable=禁用游泳模式
> littleMaidMob.gui.toggle.freedom.enable=切换到自由模式
> littleMaidMob.gui.toggle.freedom.disable=切换到跟随模式
> 
> littleMaidMob.gui.text.expboost=经验提升加速
> 
> littleMaidMob.gui.iff.title=配置对其他生物敌对性
> 
> littleMaidMob.chat.text.changeregistermode=要添加的模式更改为:
> littleMaidMob.chat.text.readyregistration=现在右键单击要添加的物品: 
> littleMaidMob.chat.text.cancelregistration=取消注册.
> littleMaidMob.chat.text.addtrigger=物品模式添加: 
> littleMaidMob.chat.text.removetrigger=物品模式删除: 
> littleMaidMob.chat.text.warningcount=警告: 该物品使用次数剩余:
> littleMaidMob.chat.text.endcount=物品剩余使用次数耗尽,物品损坏.
> littleMaidMob.chat.text.timedeath=你的 %s 不能忍受来自 %s 的痛苦
> 
> system.lmmnx.chat.text.newversion=检查到新版本
> system.lmmnx.chat.text.checkversion=前往: http://el-blacklab.net/

**Comment by Verclene** [comment]
Merged by PR #2.
