### ISSUE TITLE
[Suggestion] True knight mode

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#104]
Will maids ever learn to use a shield properly?

Would work only with sword+shield combination.
8+ blocks away from target - normal run.
Closer than 8 blocks - move towards target with shield up (slow) until close enough to attack.
Would shield against projectiles at any distance to target.
Might be awesome if they were able to bounce back nether ghost's exploding balls.

**Comment by Verclene** [comment]
Using shield : #74 Duplicate.
