### ISSUE TITLE
[Suggestion] Sword and axe attack speed difference

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#106]
Sword and axe attack speeds don't seem to be any different in maid's hands. Both are 1 hit per second. That alone makes fencers highly inferior compared to berserkers (only 2 hits versus 4 hits with iron weapon against a zombie). With #50 and #104 in mind, making different cool-downs (player has: for sword - 1 second, for axe - 2 seconds) might be of some benefit.

Or might not. If you were to make 2 seconds cool-down for axe-maid now, she would get hit back every time, because she keep rushing the target even if attack cool down is still in effect.

**Comment by Verclene** [comment]
Why BERSERKER can wait
Generally attackAI  is complicated so that I cannot modify easily.

**Comment by Shionsan** [comment]
To be clear by "cooldown" I mean that 1 second pause between maid's attacks.

You meant "why berserker should wait"? Well, so she would not rush to the target until her attack cooldown is over. Otherwise it would look like she intentionally rushes to get herself hurt: she comes close to target but does not attack for a second.

>Generally attackAI is complicated so that I cannot modify easily.

Oh well. Just thought it was a good idea.
