### ISSUE TITLE
emmmm, some problem in 1.10.2

### ISSUE THREAD

**Issue by ntrwansuiBC** [Verclene/LittleMaidReengaged#109]
emmmm....

src/main/java/net/blacklab/lmr/entity/EntityLittleMaid.java

line: 959 Biome Biome = worldObj.getBiomeGenForCoords(getPosition());
can change to 
Biome Biome = worldObj.provider.getBiomeForCoords(getPosition());
=====================================================================================================================
src/main/java/net/blacklab/lmr/entity/ai/EntityAILMAvoidPlayer.java
line:79 return avoidPath.isDestinationSame(vec3d);

why not set a new function in EntityAILMAvoidPlayer.java
just like

public boolean isDestinationSame(Vec3d vec,Path avoidPath){
        PathPoint pathpoint = avoidPath.getFinalPathPoint();
        return pathpoint == null ? false : pathpoint.xCoord == (int)vec.xCoord && pathpoint.zCoord == (int)vec.zCoord;
    }

and 
line 79 change to
return isDestinationSame(vec3d,avoidPath);

and in my 1.10.2 eclipse all ok.

**Comment by Verclene** [comment]
Methods are also changed when the target version is raised, so you do not have to post about moving methods now.
CURRENT TARGET is 1.9.4.
