### ISSUE TITLE
Error of Java

### ISSUE THREAD

**Issue by hisasaKQ** [Verclene/LittleMaidReengaged#11]
Sorry about my poor English.

When I started minecraft, an error occurred.

I think that the cause is a Java.

I white  happened phenomenon and solutions .

Error report
A fatal error has been detected by the Java Runtime Environment:
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff8f2d92177, pid=10584, tid=4324
JRE version: Java(TM) SE Runtime Environment (8.0_25-b18) (build 1.8.0_25-b18)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.25-b02 mixed mode windows-amd64 compressed oops)
Problematic frame:
C  [ig75icd64.dll+0x12177]
Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
If you would like to submit a bug report, please visit:
  http://bugreport.sun.com/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.

Environment
Forge：12.16.0.1865(latest version)
EbLib：5.1.0.1(latest version)
LittlemaidReengaged：7.1.3.6(latest version)

cause
Java environment(probably)

solution
Rewhite profile

Check a box "Executable" in profile editor,and choose latest java's directory.
(example)C:\Program Files (x86)\Java\jre1.8.0_77\bin\javaw.exe

**Comment by Verclene** [comment]
It seems graphics performance is too low or driver is outdated. Probably not a problem of LMRE.
