### ISSUE TITLE
Teleport,Exp bottles and Saddle not working

### ISSUE THREAD

**Issue by Reidlos65** [Verclene/LittleMaidReengaged#110]
Don't know where in development the carry with saddle, and click with bottle for Bottle of enchanting may have stopped working but had not seen an answer so asking here.

Release 8.1.1.102 Teleport when follow is not working.  When moving fast, Maid when following will stop if you get to far away.

**Comment by Verclene** [comment]
>Don't know where in development the carry with saddle, and click with bottle for Bottle of enchanting may have stopped working but had not seen an answer so asking here.

Interacting with bottle 'o enchanting was disabled in previous LMMNX(see that commits), and with saddle was in 7.2.0.37 (d2f89aa3479fe1d3386511d36b382a6a67d2fa7a).

>Release 8.1.1.102 Teleport when follow is not working. When moving fast, Maid when following will stop if you get to far away.

If there are no solid ground around there, maids cannot teleport. Make sure you are on safe place.

**Comment by Reidlos65** [comment]
No teleportation, I walked away when they fell into s small hole.  Just walked watching the area, never teleports.  Was in Escort Mode. is this mode applicable?

Update: seeing Teleports but they are not consistent.  Seems if you move away too fast or move in strange ways, like high jumps or other non walking ways, you will leave the maids, "I need to teleport now box"

Also getting times if they are in a big hole, they also dont get the teleport call, see video 
https://youtu.be/iOsTh75x1jw

**Comment by Verclene** [comment]
Not reproduce. Escort maid teleports when her master is far more than 12 blocks.
Report more details, or send your world so that I can research on your environment.
