### ISSUE TITLE
player(steve)'s default skin corrupted

### ISSUE THREAD

**Issue by touhouzun** [Verclene/LittleMaidReengaged#112]
Recently I'm playing with only these mods(your littlemaidreengaged)
![default](https://user-images.githubusercontent.com/31458903/29850000-fc2691dc-8d5c-11e7-8092-948eff44d215.PNG)
However,player skin(my default steve) is corrupted like these:
![2017-08-30_08 26 00](https://user-images.githubusercontent.com/31458903/29850022-3269bfee-8d5d-11e7-9719-917fe65c67ac.png)
![2017-08-30_08 26 06](https://user-images.githubusercontent.com/31458903/29850030-3af027f2-8d5d-11e7-88e8-6ce47330fa8b.png)
![2017-08-30_08 26 09](https://user-images.githubusercontent.com/31458903/29850038-40cc7c5c-8d5d-11e7-8d22-29bf2003b5ec.png)
No other mods loaded,please help me solve this.
By the way,I'm Chinese,and I'm not very good at English or Japanese_(:з)∠)_

**Comment by touhouzun** [comment]
by the way,forge2422

**Comment by Verclene** [comment]
In some specific environments, this happens if you are using Steve skin. It is caused by incompatibility with graphics card or driver. Try using Alex skin.
