### ISSUE TITLE
一応確認なのですがReengagedはGenaralGun'sに特に対応してないのでしょうか

### ISSUE THREAD

**Issue by administratorowner** [Verclene/LittleMaidReengaged#115]
1.10.2でTrigger Item Registererを弾薬に使って持たせると構えるようになりますが、（多分）発射しようとしてクラッシュしますね

1.9.4はハンドガンは一応発射音するけどほとんどあたらなかったり、アサルトライフルだと
構えてしゃべりまくるだけで打たなかったりしますが・・・

**Comment by Verclene** [comment]
特に対応してないです,本体で対応するということも特に予定しておりません.
他MOD系の武器はサポートしない方針のため,余力があるときにアドオン作るとか,相手MOD側で対応してもらうかですね

**Comment by administratorowner** [comment]
すっきりしました！どうもありがとうございました＾＾
