### ISSUE TITLE
[Suggestion?] Maid teleports alternatives

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#12]
Not sure if it's actually an issue or a good idea, but maybe it could lead to some ideas of your own, so...

As I understand it, all contracted maids have an anchor point that follows the player coordinates when on duty and just stands there when in free mode. And when too far from that anchor - maid teleports back to it (in 1.8.8 they often teleported into walls in caves, can't verify if they keep doing it in 1.9 yet). That leads to strange behaviour like: maid detects a mob far away, rushes to it, hits it once, instantly teleports back to anchor; or when in freedom mode in snowy area - they are keep going outside of anchor zone and again teleport back to it. Not like it's a problem or something, just looks weird.

In case teleporting rules are not the part of native minecraft code you use, then maybe you could apply some of these ideas:
- I remember littlemaidmob having a maid whistle in early versions. But if it's purpose was to call (force-teleport) maids to the player, then maybe it should be brought back again? With that it would be possible to remove teleporting (so it would only work if maid is stuck) or greatly increase the radius of no-teleport zone around anchor (but not sure if that wouldn't cause problems in caves).
- Dashing seem to be avalible for maids, so when maid is outside of anchor zone - make her dash to it for maybe 5-10 seconds. If by the end of that time, maid is still outside the zone - make her teleport.
- Or use two-layer model - maid dashes to anchor when she is like 16 blocks away and teleport her when she is 32 block away.
- Make maid awarness zone to match anchor zone so she wouldn't follow enemies outside of that zone.

**Comment by Verclene** [comment]
Targetting processes have been modified, so now running to outside of the range or repeat of teleporting do not happen very much. But I'll consider to make maids run into the anchor position, not teleport, when they're outside of the range.
Also, I'll make add-on which adds a whistle, maybe after major update of LMRE.
