### ISSUE TITLE
1.10.2のメイドの挙動で気が付いた事

### ISSUE THREAD

**Issue by ushichan** [Verclene/LittleMaidReengaged#124]
こちらでは初めまして、メイドmod楽しく使わせて頂いてます。

バージョン1.10.2を使用してみて気が付いた事なのですが

【ワ－プ】
土ブロック上では一定距離ごとにワ－プして付いて来ますが、砂ブロックや石ブロック上にはワープして来ないみたいです。
離れた距離で近くに土ブロックがあればそこにワ－プして来ますが
ある程度までの距離内の場合でそれ以上に離れるとその場で足踏み状態になり、
その状態になると歩いて付いてくる範囲内まで近寄らないと寄ってこなくなります。
何となくですが土ブロック以外のブロック上にワ－プ出来なくなっているのかなと。

【戦闘】
戦闘中に始めは距離を取ると此方に寄ってくるのですが
何度かタゲを取るとそのうち辺りの一定範囲内に完全に敵mobが居なくなるまで此方の方へ寄ってこなくなります、
ワ－プもしなくなり砂糖で呼び寄せる事も出来なくなります
その状態でタゲを取ると行動不可範囲に移動するまで敵mobを追いかけるようになりました。
その際小刻みに反応音（敵性mobを知覚時にする反応）を繰り返します。

以上です
これからも開発頑張ってください、微力ながら応援しております。

**Comment by Verclene** [comment]
タスク管理の都合上issueを分割しました.
今後はそちらで対応します.
