### ISSUE TITLE
Occasional Crashing on Server & other issues [1.10.2]

### ISSUE THREAD

**Issue by tetsune** [Verclene/LittleMaidReengaged#129]
Hello,

I have had some small issues with maids and my modded server. 

1. When exploring far away, my sister said the server would crash. Upon investigation, this is what came up:

https://gist.github.com/tetsune/252b5577d215ec148b37e380f7860e7b

Looks like another SpongeForge thing, I will bring this up on their end if this is true.

2. This may be a bug, but Maids never leave Bibliocraft chairs... I have tried to pull her out, but she stays.
Also, when breaking the chair, it also causes a crash. I will try to find the crashlog for that one or reproduce to get you information. Possibly a Bibliocraft issue.

3. Is there a way to stop the natural spawn of Maids and have them only spawnable via eggs?

**Comment by Verclene** [comment]
POST AN ISSUE FOR EACH REPORT, DO NOT POST MANY FOR ONE ISSUE. Or I cannot close tasks by fixing.
