### ISSUE TITLE
Vanilla player texture messed up

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#13]
Seems like LMMRE messes up vanilla player textures in some way. That bug was in previous versions too.

With LMMRE mod > https://s31.postimg.org/51xcafw7f/2016-04-20_19.28.56.png
Without LMMRE mod > https://s31.postimg.org/7tpsspwor/2016-04-20_19.32.48.png

Does not affect player skin if texturepack is used.

Just in case, list of other mods I use:
DynamicLights-1.9.jar
FinderCompass-1.9.jar
jei_1.9-3.2.10.185.jar
OptiFine_1.9.0_HD_U_B1.jar
WorldHandler-1.9-3.1.jar
Xaeros_Minimap_1.8.7.1_Forge_1.9.jar

I do not own minecraft and use different launcher. Wanted to join your server, but couldn't. Maybe that could be a reason too.

**Comment by Verclene** [comment]
Are you using Steve skin? Different texture size may cause incorrect rendering. This problem occurs in the vanilla rendering system, so I cannot solve this. Please use Alex skin.
