### ISSUE TITLE
Attempt to Port to 1.12

### ISSUE THREAD

**Issue by Poppyanimal** [Verclene/LittleMaidReengaged#143]
Hello, for the past week I've been working on porting Little Maid Reengaged and the accompanied library to 1.12 for personal use with a group of friends since we have been following the project since 1.7.10's release. I was wondering if I could ask some questions about the mod's implementation so I can fix one of the more confusing crashes I've encountered a bit easier: 
https://gyazo.com/66671d477e1164d4e4dca52af7139a56.gif 
I am not an experienced modder, but I dont want this mod to slowly die out. Sorry for using the issue box to get a hold of you but I couldnt really find another way.

**Comment by Verclene** [comment]
Then you have better prepare your project on your GitHub repository. Post issue(s) there, and I can help you with your trouble.
Now I am working on this repository, so any discussions of your project should not be held here.
