### ISSUE TITLE
Escorter and freedom classes aren't mentioned in GUI

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#16]
Escorter and freedom classes aren't mentioned in GUI. When in those modes only health and armor (if equiped) is shown.

Was it meant to be that way?

**Comment by Verclene** [comment]
Not bug, but shoud they be shown again?
The 'Escort' has no special features without collecting items, and the 'Freedom' can be distinguished by a GUI button.

**Comment by Shionsan** [comment]
I suppose they should. It is her current status after all. And to have it shown instead of "if not shown, then it's an escort" is a bit more user-friendly. Also "collecting items" is a special feature worth mentioning, as other classes don't do that.
