### ISSUE TITLE
Unequiping torches doesn't work properly for maids now?

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#19]
http://imgur.com/jaMRHGJ

With Dynamic Lights mod, every maid, that held a torch even once, keep emmitting light after unequipping it. On world restart lights go away. This suggests that "unequip" function (at least for torches) doesn't work properly now.

It could be just an incompability with Dynamic Lights mod, but I don't remember it happening before 7.1.5.19.

**Comment by Verclene** [comment]
I imported sources of Dynamic Lights Mod and tried debugging, and I found that the DLM has an unusual way to modify brightness. There seems to be no logical error in the processes maids equipping items, so the DLM may have some incompatibility or bugs. Currently I cannot do anything about this matter.
