### ISSUE TITLE
[Suggestion] Disable/prevent friendly fire for archer maids

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#20]
Archers cause friendly fire quite often. Especially in a team with some melee fighter class. Is it possible to disable friendly fire for archer maids or maybe prevent them from shooting if friendlies (player or maids of the same player) are in the line of fire?

**Comment by Verclene** [comment]
It seems hacking into arrow entities is needed. I'll put off disabling FF.
