### ISSUE TITLE
アーマーテクスチャーの再配布願い

### ISSUE THREAD

**Issue by Modchu** [Verclene/LittleMaidReengaged#21]
LittleMaidReengagedで同梱されているアーマーテクスチャーをうちのMultiModel_DefaultModelSetに同梱して配布したいのですが許可いただけませんでしょうか？
元々あったアーマーテクスチャーに追加されていると思われます。

**Comment by Verclene** [comment]
LMRE標準同梱テクスチャの抽出および利用は再頒布及び改変とみなし,ソースコード同様非営利に限りご自由にして頂いて構いません.
ただし,7.1.5.19時点ではadditional_Orignのアーマはdefault_Orignと同じものです.

**Comment by Modchu** [comment]
許可いただきありがとうございます。
