### ISSUE TITLE
Maids don't have models

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#3]
I have these two installed:
EBLib-5.1.0.1-1.9.jar
LittleMaidReengaged-7.1.2.4-1.9.jar

"Wild" maids are invisible (have no models?). Their shadows are visible and they make sounds.
Maid spawned by an egg has default black model and is visible.

Do I need some other mod?

**Comment by Shionsan** [comment]
https://s21.postimg.org/w9jin4vyf/2016-04-16_17.44.24.png
At the left - hired maid. At the right (shadow) - wild maid.

**Comment by Verclene** [comment]
Fixed. Please update to 7.1.3.6.
This package will also fix transparent wild maids automatically.
