### ISSUE TITLE
[Suggestion] Fencer/berserker attack range increase

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#32]
Attack range for sword/axe maids seems to be too short, as maid takes a hit almost every time she attacks. As player you can defeat monsters without taking any damage, at least if it is 1 on 1. But with maids it's like they hit mobs with their heads, instead of weapons.

**Comment by Verclene** [comment]
First attack range can be increased, but maids don't go back so they're attacked after all. It is too hard to make them attack then return immediately, even I did that, they would be too smart, which might corrupt the game balance.
