### ISSUE TITLE
Crash when Farmer plants beetroot

### ISSUE THREAD

**Issue by Aizenns** [Verclene/LittleMaidReengaged#34]
申し訳ありません、英語能力の不足でよくわからない題名になってしまっています・・・。
バグの内容ですが、農業モードのメイドさんに**ビートルートの種**を持たせたところ、メイドさんがそれを植えた瞬間にクラッシュしてしまいました。
また、新しく作ったワールドで、同様に試してみたところ小麦の種からビートルートに切り替わって植え始めた瞬間同様にクラッシュしてしまいました。
クラッシュしてしまったワールドは何度試しても読み込んだとたんにクラッシュしてしまうので植えたビートルートの苗が何かおかしなことになっているのでしょうか？
対応よろしくお願いします。

**Comment by Verclene** [comment]
Report: https://github.com/Verclene/LittleMaidMobNX/issues/39

**Comment by Verclene** [comment]
7.1.6.35をベースに,該当のバグを修正した7.1.7.39を公開しましたので更新をお願いします.
