### ISSUE TITLE
7.1.8.41 can't load old world

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#41]
Something similar happened before. Log gets stuffed by the same error over and over again untill you force-close the game. New worlds are being created normally.

Part of that log here: http://pastebin.com/raw/q6sAG8NC

Should I upload that world somewhere (43mb)?

**Comment by Verclene** [comment]
This bug was already reported on LMMNX, but unfortunately I cannot find the solution at all so this still has been unsolved. I can say only that this seems tend to happen more on flat worlds...
