### ISSUE TITLE
Tall maids don't look at the player properly

### ISSUE THREAD

**Issue by arcusmaximus** [Verclene/LittleMaidReengaged#42]
If you get close to a tall maid, she'll look over your head instead of facing you. She thinks she's a small maid who has to look upwards to face the player.

This can be easily reproduced by picking the Stef or Steve model and standing close to it. The "Beverly7" multimodel by voms is also affected (I ported it to LittleMaidReengaged: https://dl.dropboxusercontent.com/u/60681258/littleMaid/littleMaidMob-Beverly7-190.zip).

The bug can be fixed by adding a call to `setSize()` in `ModelConfigCompound.setTextureBox()`.

**Comment by Verclene** [comment]
Loading multimodel has become side-dedicated. The setSize() needs to be called on server, but custom maidmodels can be loaded only client-side.
To fix this bug, syncing size of Entity is required. However, by adopting it, maid sizes can be hacked. So I have not fixed this on purpose.
