### ISSUE TITLE
Maids have difficulty chasing mobs if player is behind them

### ISSUE THREAD

**Issue by arcusmaximus** [Verclene/LittleMaidReengaged#43]
If a maid is tasked with killing mobs or shearing sheep, she has great difficulty on deciding whether to run to the mobs or come back to the player. She shakes her head from side to side and walks around aimlessly. It gets even worse if the player is holding sugar.

Can be reproduced as follows:
- Place a sheep and walk 15 blocks away from it.
- Place a maid near yourself.
- Task her with shearing, so that she has to walk away from you to get to the sheep -> she starts walking around slowly and shakes a lot, never reaching the sheep.
- Run/fly past her and go stand next to the sheep. Suddenly she approaches it much more quickly.

**Comment by Verclene** [comment]
Now targeting processes is begin adjusted, and will be improved in next update.　#30
