### ISSUE TITLE
minecraft1.9.4に対応して頂ける予定は有りますか？

### ISSUE THREAD

**Issue by ghost** [Verclene/LittleMaidReengaged#44]
minecraft forge1.9.4-12.17.0.1960にLittleMaidReengaged-7.1.8.41-1.9を導入してもクラッシュしてしまいます。いつか1.9.4にも対応して頂けますか？

**Comment by Verclene** [comment]
メジャーアップデート作業が終わり次第対応します.実装の都合上同一パッケージ化ができない点ご了承願います.

**Comment by Verclene** [comment]
https://github.com/Verclene/LittleMaidReengaged/releases/tag/8.0.1.67

**Comment by Verclene** [comment]
とりあえずbetaとして出してます.コンパイルエラーチェックだけ済ませてありますが,不具合あればご報告ください.

**Comment by ghost** [comment]
早めに対応して頂きありがとうございます
minecraft1.9.4でプレイしてるのですが、1.9の、1*1ブロックの空間に大量のmobを押し込むとかなりラグが生じる。チャンク生成時のパフォーマンス低下。などのバグが嫌でダウングレードしたくなかったのでとても助かりました。
また不具合等あったらご報告します
