### ISSUE TITLE
[Suggestion] No more TNT-suicide maids!

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#46]
Never used a suicide maid. And never will. Because it's just cruel. But if you were to make TNT-maids not to explode, but to drop lit TNT on hit and run away... wouldn't that be awesome? And this feature would require TNT-awarness, that every maid class would benefit from. Like everyone who doesn't have a shield - would run away, and those who have - would block the explosion.

**Comment by Bakudankun** [comment]
I don't want TNT-maids feature to be removed. It's because I like it as a joke though I've never used it too, and it's rarely enabled by accident (ah, well, my name and avatar are not concerned).
I think awareness of exploding TNT (and creepers like other mobs) would be nice feature if implemented.

**Comment by Goujer** [comment]
I wouldn't get rid of them, they are fun to mess with when in Creative mode and while a TNT dropper maid sounds like an interesting idea I don't think it should replace TNT-suicide maids all together.

**Comment by UnixRonin** [comment]
I'm in the school of thought that suicide-bomber maids are in horribly poor taste.  It's a feature I for one will **never** use.  It's just wrong.

**Comment by Verclene** [comment]
It can be expected that unfortunate accidents will be happen when a maid switches to the "Bomber" automatically, so I'll make an exception for switching to bomber. But a feature called Bomber will not be get rid of, because after this modifying, I can say like this: "Don't use it if you don't want to do."
