### ISSUE TITLE
[Suggestion] Medic class

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#48]
Suggestion #45 gave me another idea - how about you remove maids self healing ability? If you were to, that would present several more maid behaviour and interaction possibilities:
- player would have to heal maids with sugar or some other sweet stuff, like maybe some candy (additional mod?) that would heal better than sugar;
- badly hurt maids would fall back or switch to maid-in-distress mode;
- and the most interesting possibility - medic class.

There are already a healer and feeder classes, but with dedicated slots you could unite them into a single medic class, that would use any food, potions or sugar respectively if the need arises. It could also be the only class with self-healing ability. It would usually behave like escort class - being afraid of monsters and calling for help if there is no path to anchor-point, but only until someone from her awarness area takes damage or gets hungry - then she would turn into fearless resquer, rushing to the hurt ones with healing items in hands.

**Comment by Shionsan** [comment]
Algorithm of deciding who to heal/feed would be a challenge though. Whenever player healing should be a priority and which maid should be (fully?) healed first.

Item usage priorities could be managed by the type of an items are in dedicated slots based on 4 types - potions, throwable potions, food and sugar. Main hand would be top priority, offhand - second, and items in apron being chosen last with priority on healing items over food if player has less than 50% HP.

**Comment by Verclene** [comment]
> how about you remove maids self healing ability?

Nope. Healing with sugar is one of the most emphasized features - and maids' characters(!).

**Comment by Shionsan** [comment]
I wonder if I have failed to explain this idea correctly. I never meant to remove sugar use completly, but to replace [maids' self healing] with [player or medic-class maids using sugar on hurt maids to heal them]. Sugar that maids would hold in their aprons would still be consumed as a weekly payment, but only medics and player would be able to heal maids with it.

**Comment by Verclene** [comment]
I've got it, SO the answer is "No." I think what is the core of maids' "healing" feature have been SELF-healing, not just recovering HP(even on old versions). This is one of maid's characters, which I don't want to lose.

**Comment by Shionsan** [comment]
Understood.

But what about [healer+feeder=medic] then? Both classes are meant to use items on player, so...

Actually I think it would be even better to unite them all into an escort class, as that would be the most apropriate. She follows you, cleans up the area and takes care of you - exact definition of a maid, isn't it?

hmm.. So if I were to rephrase all that:
Escort + Healer + Feeder = The Maid (default class)

Good? Bad? Should I put it into another issue?
