### ISSUE TITLE
[Bug?] Berserkers hate armour stands

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#49]
For some reason berserkers really hate armour stands. They keep attacking them in survival mode endlessly (attack speed isn't fast enough to destroy it) and destroying them in creative mode.

**Comment by Verclene** [comment]
Right-click a maid with book, and then mark ArmorStand as "FRIENDLY". I'll take measures on next update.

**Comment by Shionsan** [comment]
Hmm. That didn't help. ArmourStand is set to friendly, but berserker still keeps attacking it.
