### ISSUE TITLE
Apron bugs (maid GUI)

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#5]
- There seems to be a difference in whoever puts item in an apron (maid or player): maid do not add picked items to stacks that was put there by player
- GUI shows only status/class and armor. Health is missing (already fixed in 7.1.4.7?)
- You can't strip maids armor without holding shift now (is it normal?)

**Comment by Verclene** [comment]
> maid do not add picked items to stacks that was put there by player

Isn't that items damaged?

> GUI shows only status/class and armor. Health is missing

Fixed in 7.1.4.7.

> You can't strip maids armor without holding shift

Currently it is one of specifications.

**Comment by Shionsan** [comment]
> Isn't that items damaged?

Only stackable items are affected. Checked this bug again: damage doesn't seem to be an issue, free slots are.

Take some stackable item (for example wood), put it in maybe 5th slot and leave any of first 4 slots empty. Any wood picked by maid later would go to first free slot instead of the 5th slot that already has some wood. I can't point the error in the code, but algoritm for selecting where to put an item gives priority to first free slot instead of checking if maid already has non-full stacks of this item in other slots.
If you'd put wood in the first slot and then drop some of the same item at maid, she would add them to the stack in first slot as she should.
