### ISSUE TITLE
[Bug?] Maid with a torch vs Torch layer

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#51]
Latest OptiFine now includes the Dynamic Lights mod feature. But with new class change trigger it bugs out the idea of [Escort maid] with a torch, as that maid instantly becomes a [Torch Layer]. And putting a torch in second slot automatically moves it into first. Is it possible to make only the first slot to be a trigger? Or at least to have torch layers to keep the last torch they have?

**Comment by Shionsan** [comment]
Seems the trigger only works when item is placed in the slot. Like with the archer - when bow is removed or gets broken - class stays unchanged, same with the [Torch Layer]. Btw, "placer" would be a better word, as "layer" has more of a "lay down on a bed" meaning.

Item removal should also become a trigger and switch maid into an escort class.

**Comment by Verclene** [comment]
Remove all torches and then put them on the offhand slot. Or nevertheless does maid keep being Torch"Placer"?

**Comment by Shionsan** [comment]
I've kept placing torch in main hand slot first. That triggered [Torch Placer] class change. Simply removing them doesn't change the class, so when I placed torches in offhand - they were moved back to first. Had to place some random item in the main slot to change it to [Escort class] first.

Complex trigger that would work on item removal or [on tool break] is in order (especially for battle classes). By complex I mean a check if maid has another item/tool/weapon to replace the broken/used one with before changing back into escort class.

And can you put current class name at some separate location of UI? That was mainly a reason I misunderstood this as a bug.

**Comment by Verclene** [comment]
> And can you put current class name at some separate location of UI? That was mainly a reason I misunderstood this as a bug.

Well, mode string on GUI is often hidden. I'll improve it. Closing to be move to #57 .
