### ISSUE TITLE
[Bug?] 1.6.2 models do not work anymore?

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#53]
Until now I used littleMaidMob-1_6_2-3M_v1 model/skin pack (the one you used before in your videos). But with latest update it doesn't show up in model selection screen.

Who do I have to kill to bring those models back? They were cute T_T

**Comment by Verclene** [comment]
On 8.0.1.67, the coremod seems to be disabled due to build settings failure. Will be fixed on next beta update.
