### ISSUE TITLE
[Suggestion] Gunpowder autouse for berserkers

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#54]
As the title says - if berserker has a gunpowder in her apron and isn't in Hot mode yet, she should use it when enemy is in sight. Why? Because hot dual wielding berserker is a PERFECT berserker.

**Comment by Verclene** [comment]
Berserker shouldn't be perfect because she is just mad. Fencer might be smart and do such actions rather than Berserker.

**Comment by Shionsan** [comment]
I meant that it fits the berserker very much - "get drugged and go on a mad rampage". I didn't suggest fencer to do that for the same reason - it wouldn't fit them, and as you said - they might be smart, so they shouldn't use drugs on their own. But I suppose everyone sees them differently.
