### ISSUE TITLE
[Bug] Action priorities and walking bugs

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#55]
- [Idle actions] should be interruptable.
- Head tilt angle of escort class maids should be reset on item pick up
  Escort maid would ignore an item dropped near her until she completes the [random movement] or [idle standing] action. Even through she does look at the item, she keeps walking by it. She also keeps looking down when item is picked up.
- [Stop action] should happen before [Attack action]
  Fencer keeps making 360 turns on attack. My assumption is that there is no [stop-packet] being sent on attack or it is being sent after the attack, what creates 1 tick server-client differences of maid coordinates, and results in those 360 turns.
- [Bow streching] action should be stoppable.
  Archers keep shooting in the direction they face or in a direction of an entity that is first in their check list, as they sometimes are hitting sheeps with perfect accuracy that are very far away. That happens when their original target dies when [bow streching] action is started but before the shot is made.
- ???
  Berserkers seem to have a unique(?) ability to follow their target when it is outside their area, as they keep moving towards it slower than usual and spamming "attack" voices.

**Comment by Verclene** [comment]
> [Idle actions] should be interruptable.

What do you mean by "Idle actions"? 

> Even through she does look at the item, she keeps walking by it. She also keeps looking down when item is picked up.

I'll modify maid tilting her head.

> [Bow streching] action should be stoppable.

Related problems seems to happen due to my misunderstanding for using hand. To interrupt targetting by bow, I have to call resetActiveHand(), not stopActiveHand(). I'll fix them and maids will stop shooting unnaturally.

> Berserkers seem to have a unique(?) ability to follow their target when it is outside their area, as they keep moving towards it slower than usual and spamming "attack" voices.

I see, more targetting fixes are needed.

**Comment by Shionsan** [comment]
> What do you mean by "Idle actions"?

Random walks within their area and when they just stand at one point looking at random things. Those actions seems to be uninterruptable, as, for example, freedom maids would look at (target) a dropped item, but still keep walking to "random-idle-walk" coordinates and only after that is done - she would come to pick up that item. Same with "idle-standing" - it takes somewhere around 3-5 seconds until maid comes to pick up items dropped near her.

This actually might be another misundestanding of mechanics on my part, as it might be related to dropped item timeout. Like when player drops some items and can't pick them up for a few seconds.

**Comment by Verclene** [comment]
> freedom maids would look at (target) a dropped item, but still keep walking to "random-idle-walk" coordinates and only after that is done - she would come to pick up that item.

This is due to Vanilla AI specifics and restriction. I cannot think of any good solutions, so please let me say "that is one of specification." 

And I forgot to reply:

> Fencer keeps making 360 turns on attack. My assumption is that there is no [stop-packet] being sent on attack or it is being sent after the attack, what creates 1 tick server-client differences of maid coordinates, and results in those 360 turns.

No such phenomenon appear... Isn't it caused by too heavy processing or other mods' failure?
Originally, what called "stop-packet" does not exist, and I do not have to sync Entity's coords manually because the world does it automatically.

**Comment by Shionsan** [comment]
> Isn't it caused by too heavy processing or other mods' failure?

It were happening a lot when fencer (with a shield in off-hand) was fighting skeletons I've been summoning in a long corridor in creative mode. I also noticed that fencers sometimes were not follow the skeletons in a straight line, but moved in zig-zags (new feature?).

There are some "yet-unoptimised" mods in my pack, like RTG and I have OptiFine's dynamic lights enabled, but I don't think that was the reason in this particular issue (all visible terrain was already pregenerated and noone held a torch around).

I have a mod [ВращениеЗемли-1.9.4](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1289314-1-4-7-1-9-4-vrashenie-zemli-majnkraftskaya-longer) that makes in-game time go slower though. But not sure if it can affect mobs.

I'll check this again a bit later.

**Comment by Verclene** [comment]
> I also noticed that fencers sometimes were not follow the skeletons in a straight line, but moved in zig-zags (new feature?).
> There are some "yet-unoptimised" mods in my pack, like RTG and I have OptiFine's dynamic lights enabled,

I highly doubt whether this is LMRE's bug. Please check without other
mods(except EBLib and Forge). Note that I cannot fix ALL incompatibilities.

**Comment by Shionsan** [comment]
Checked it. No mod is responsible. Nor the CPU load is a reason to it. The bug is related to mobs coming outside the maids' awarness area after the fight is started. To see it for yourself - make a fencer, switch her to freedom mode and keep spawning skeletons further away from maids' anchor point. At the edge of anchored area few new "strange" behaviours will surface, like this 360 turn, which is actually a maid trying to go back to her anchor point, but switches back to attack at the next tick. Another new bug is that sometimes maid chooses not to follow/attack the enemy after starting a fight once it moves outside of awarness area, what ends up with a situation where skeleton keeps shoting the maid, while said maid does nothing but [idle actions].

So even "more targetting fixes are needed." At least have to teach maids to finish the fight they started before going back to anchor or ignoring the enemy.

**Comment by Verclene** [comment]
I see, I'll do tests later. To confirm, you are using 8.0.1.67 right? By the way, this issue contains more than 1 problems. To manage tasks to do, this will be closed and rearranged into some issues.

**Comment by Shionsan** [comment]
> To confirm, you are using 8.0.1.67 right?

Yes.
