### ISSUE TITLE
[Suggestion] Archer's arrow choice and pick up

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#56]
Since some 1.9.x version enchanted arrows were added to minecraft. And with that some way to choose which arrow to use is in order. I suppose it's not a problem now with dedicated slots avalible.

So my suggestion is to have archers use arrows placed in offhand slot, and put first avalible arrows from apron there if none are placed.

Also have to think about what to do if maid has no arrows left. Right now they just do idle actions while watching their possible targets.

Maybe when archers has no target/arrows (in idle mode) and some stuck/dropped arrows are near them - they should pick them up like escorts do with "trash"? But for that to work properly in battle [idle actions] should become interruptable first (#55).

Might not be bad to have them switch class to melee if they are out of arrows, no stuck/dropped arrows are in sight and they have weapon in their apron.

**Comment by Verclene** [comment]
> So my suggestion is to have archers use arrows placed in offhand slot, and put first avalible arrows from apron there if none are placed.

This process is done by ItemBow, so I have to do nothing for this.

> Right now they just do idle actions while watching their possible targets.
> Maybe when archers has no target/arrows (in idle mode) and some stuck/dropped arrows are near them - they should pick them up like escorts do with "trash"?

I'll make archers stop acting when they have no arrows.

**Comment by Shionsan** [comment]
> I'll make archers stop acting when they have no arrows.

What might result in archer being killed, if that were to happen during a fight. Very bad idea. She should at least run away or switch to another battle class (fencer) if she has a weapon (sword) in her apron.

**Comment by Verclene** [comment]
> What might result in archer being killed, if that were to happen during a fight. Very bad idea. She should at least run away or switch to another battle class (fencer) if she has a weapon (sword) in her apron.

Don't use Archer if maid have few arrows. Such smart AI should be provided by any add-on, not by LMRE core. Maids shouldn't be perfect or fully useful, which is the original concept of LMM. Also that is the reason some add-ons like "Maid battle manulal" existed for previous LMM versions.

**Comment by Shionsan** [comment]
~~So maids are meant to be dumber than cows or sheeps...~~ Now that's a dissapointment. A big one.

"Infinity" enchantment it is then...

**Comment by Verclene** [comment]
https://github.com/Verclene/LittleMaidReengaged/commit/3204b60adfa056019914d0ba5ff3ed1e74c340a6
