### ISSUE TITLE
Targetting issues near the edge of tracking area

### ISSUE THREAD

**Issue by Verclene** [Verclene/LittleMaidReengaged#59]
#55 When the target is pushed out of maid's tracking area, she resets targetting, causes some strange behaviours.

**Comment by Shionsan** [comment]
You will have to switch from "anchor area" concept to "maids' awarness area" for battle classes to fix that. So only when there is nothing for maid to kill in her awarness area she would return to or follow the anchor. That of course would lead to more "lost maids" cases, but there wont be any bugs this way. And if maid is "lost" (too far from anchor point) - you could just teleport her back (if in freedom state and player is far away) or switch her to distress mode.
