### ISSUE TITLE
Torch Layers no longer place torches while riding on player

### ISSUE THREAD

**Issue by arcusmaximus** [Verclene/LittleMaidReengaged#64]
In Minecraft 1.7 (LMMX), maids in "Torch Layer" mode could place torches while riding on the player's shoulders.

In Minecraft 1.8 (LMMNX) and 1.9 (LMMRE 7.1.8.41), they only place torches while walking, not while riding. Was this disabled intentionally or is it a bug? (I didn't see it mentioned in the change logs)

In Minecraft 1.9.4 and 1.10 (LMMRE 8.0.1.67), maids cannot ride the player at all. (Rightclicking a maid with a saddle opens her inventory instead)

**Comment by Verclene** [comment]
> Was this disabled intentionally or is it a bug? (I didn't see it mentioned in the change logs)

I think I haven't disabled it on purpose, so Vanilla or Forge have changed something...
Anyway, this will be not fixed for a long or short while because I have disabled maid ridding due to another unsolvable bug...

**Comment by arcusmaximus** [comment]
That's too bad. Hopefully maid riding can be fixed at some point, it's a useful feature :)
