### ISSUE TITLE
メイドさんが廃坑で線路に引っかかってついてこない

### ISSUE THREAD

**Issue by ghost** [Verclene/LittleMaidReengaged#65]
メイドさんが線路の上を通らないので、廃坑でついてきてくれません
8.0.1.67 minecraft1.9.4

**Comment by Verclene** [comment]
バニラのWalkNodeProcessorの仕様のようです.対策を検討してみます.

追記:思ったより簡単に解決できそうなので,次のアップデートでは治っていると思います.
