### ISSUE TITLE
1.10.2 support

### ISSUE THREAD

**Issue by Zadnicaff** [Verclene/LittleMaidReengaged#67]
Not actually a bug but I guess it would be nice to have 1.10.2 added to the list of launchable versions. Especially since EBlib already has it...

**Comment by Verclene** [comment]
Please do not hurry. I'm working for the last update on 1.9. Master branch will be updated to 1.9.4/1.10x after releasing it.

**Comment by Zadnicaff** [comment]
Nice to hear that. Thank you for quick reply and sorry for bothering.
