### ISSUE TITLE
1.8.9には対応していない？

### ISSUE THREAD

**Issue by Bakudankun** [Verclene/LittleMaidReengaged#69]
READMEには「for MC1.9(expected)/1.8.9」とありますが、1.8.9に対応しているバージョンのLMREはあるのでしょうか？

**Comment by Verclene** [comment]
私情によりダウングレードに手を付けられそうにありません…8月に入ったらコンパイルエラーのみ修正した人柱版くらいは出せそうですが,サポートできる可能性は極めて低いです.

**Comment by Bakudankun** [comment]
できれば人柱版でも対応して頂けると嬉しいです（竹MODが今のところ1.8.9までなので……）。
もし対応する余裕が無さそうなのであればREADMEを修正した方が良いと思います。
宜しくお願いしますー

**Comment by Bakudankun** [comment]
？？？
よく考えたら1.8.9なら引き続きNX使えばいいですね。僕は一体何を悩んでいたんだろう……

というわけで対応しなくて大丈夫です。済みません。
しかしやはりREADMEに1.8.9対応のように書かれているのは要らぬ誤解を生むと思うので、サポートできないのであれば修正した方が良いかと思います。
