### ISSUE TITLE
[Suggestion] Maid's voice overlap

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#7]
Maids are using sugar the moment they are damaged. There is no delay and with a voice pack maids sound a bit masohistic, which might be good for some, but is illogical. They also voice-spam when they're about to attack.

Is it possible to make maids speak like only once per second, so voices of a single maid would not overlap so much?

**Comment by Verclene** [comment]
Adjusted on 7.1.4.9/7.1.4.10.
