### ISSUE TITLE
農耕を任せたメイドさんが種をチェストに搬入してくれない

### ISSUE THREAD

**Issue by Rizenbuffe** [Verclene/LittleMaidReengaged#79]
小麦の種がチェストへの搬入対象になっていないようで、長期間小麦の農場を任せておくとメイドのインベントリが種で一杯になってしまいます。
LittleMaidReengaged-8.0.1.67　Minecraft1.9.4

08/12:追記します
ニンジンやジャガイモも搬入対象となっていないようです。ビートルートと小麦、青くなったジャガイモ、その他作物では無い雑多な品（羽やケーキなど）は搬入してくれます
"植えられるもの"を搬入しないようになっているのでしょうか

**Comment by Verclene** [comment]
だいぶ今更感がありますが…
IPlantableに該当する(植えられる)アイテムは残すように設定されています.ただし後ろの方のスロットは強制的にチェストにしまうようになっているのでご確認ください.
