### ISSUE TITLE
Crash on enemy kill and broken world as result

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#8]
Sometimes game crashes when maid defeats a mob as a fencer. After few crashes I ended up with "[broken world](http://shion.ru/maidlands.zip)" - the game is stuck in "Building terrain" state, while endlessly writing log with exceptions. Here's a beginning of one such log: http://pastebin.com/raw/gT3Bb8fv (line 892 and below might be of interest).

The fml-client-latest.log right after kill-crash: http://pastebin.com/raw/jRrnn7m1 and another one http://pastebin.com/raw/hBhkAEed

Before that, my first world (with invisible wild maids) ended up "broken" in a similar way right after I switched to 7.1.3.6. Don't have logs/save from that time. Maybe "Auto-fix" is somehow related?

By the way the broken world loads fine without LMM.

**Comment by Verclene** [comment]
Caused by an attribute 'LUCK' was not registered.
Auto-fixing transparent maid may not be related.
