### ISSUE TITLE
To update

### ISSUE THREAD

**Issue by xiaowang266** [Verclene/LittleMaidReengaged#82]
When will you be able to update this 1.10.2 to the mod version?

**Comment by Shionsan** [comment]
There were no changes since september. Project dropped?
If so, is it possible to compile a release for 1.10.2 version before The End?

**Comment by Verclene** [comment]
Forge for MC 1.11 has been released, I'll work for it after finishing updating for MC1.10.2. Now I'm planning big change of the specification. For instance, maid teleporting causes annoying bugs will be temporarily removed.

**Comment by Verclene** [comment]
Why there have been never commits for this several months is issues(also ones are not posted here) have been many and detailed. Dealing with all of them will be too much if blocks are required, and I don't want to such detailed and inflexible handlings. So I decided to remove some features which requires hard bugfixes.
