### ISSUE TITLE
what happened to mmmlibx ?

### ISSUE THREAD

**Issue by Royal-Jelly** [Verclene/LittleMaidReengaged#86]
I have been unable to use these models with LMMR: https://www.dropbox.com/sh/4k60qg37lfqxfu6/AAA4BE26MARp91OVtPj3Lhnla/littleMaidMob-KemonoMdl1.6.2a.zip?dl=0

Any feedback would be apreciated, and thank you for your time

**Comment by Verclene** [comment]
Which version of LMMR do you use?

**Comment by Verclene** [comment]
Duplicate #53 if you have 8.0.1.67

**Comment by Royal-Jelly** [comment]
I am using a self compiled version from [tatsu's fork](https://github.com/tatsu011/LittleMaidReengaged/commit/f4ee8159a45c0894a033c16373433e7c6406ffb9), i messed with his buildscript to see if i could get mmmlibx to compile under 1.10.2 (I assumed it would compile without error)

seems to me like i should leave the complicated code work to those who know what they are doing, thank you again and have a wonderful day/evening
