### ISSUE TITLE
Wont work on 1.10.2

### ISSUE THREAD

**Issue by NanoHeart** [Verclene/LittleMaidReengaged#88]
I've looked into the code, and the mod will not work on 1.10.2 while your lib will work on 1.10, and 1.10.2. Please change to `
	public static final String DOMAIN = "lmreengaged";
	public static final String VERSION = "8.0.4.91";
	public static final String ACCEPTED_MCVERSION = "[1.9.4,1.10.2]";
	public static final int VERSION_CODE = 1;
	public static final String DEPENDENCIES = "required-after:Forge@[1.9-12.16.0.1819,);"
			+ "required-after:net.blacklab.lib@[5.2.0.3,)";`

`

**Comment by Verclene** [comment]
Dupe & known, closing
