### ISSUE TITLE
Pathfinding of a very slim maid

### ISSUE THREAD

**Issue by Shionsan** [Verclene/LittleMaidReengaged#9]
https://s23.postimg.org/o36mz14jv/2016-04-17_21.56.03.png

Red square - starting position of a maid.
Cake - player position.

When maid tries to follow the player in this situation, she doesn't try to go around. Instead she tries to squeeze through the corner in the middle.

Thanks to this bug, maids get stuck in mines a lot. I wonder if that is fixable.

**Comment by Verclene** [comment]
NodeProcessor uses vanilla WalkingNodeProcessor. That is not a bug of LMRE.(Try with sheep and wheat)
I have little time to reassemble NodeProcessor...
