### ISSUE TITLE
Minecraft1.10.2で・・・ 

### ISSUE THREAD

**Issue by sion3100** [Verclene/LittleMaidReengaged#90]
マイクラ1.10.2でlittle maid reengagedをしようとしてるのですが、やり方がいまいちわかりません。教えていただけますか？

**Comment by Verclene** [comment]
あなたの書き込みは正常に投稿されています. #89 
対応済みとしたissueは"Closed"のページにあるのでご確認の上投稿するようお願いします.
https://github.com/Verclene/LittleMaidReengaged/issues?q=is%3Aissue+is%3Aclosed
