### ISSUE TITLE
FINISHED DIVIDE ISSUES

### ISSUE THREAD

**Issue by Kohji-Shimazaki** [Verclene/LittleMaidReengaged#92]
MC1.10.2対応版完成後の依頼ですが、MC1.11.xでの改善点があります

(移動完了しましたので消去致しました)

P.S.
長文失礼しますが,そちらから要望を分割希望したい場合はCloseせず返信のみで行って下さい
確認次第カテゴリ毎に分割(1を残して,2は新しく移動)しますので宜しくお願い致します

**Comment by Verclene** [comment]
>各ブロック上にmobが合計24体(デフォルトの場合)を超えると超えてしまった分のmobが窒息発生されてしまい、時には重なり合っていたメイドさんが窒息でやられてしまう事態が起きてしまいます

テレポート時の対策は簡単にできますが(もっとも今機能刷新のために削除してるんですがね…),"押されたとき"の挙動を実装するのがすごく面倒くさいのです.Eventとか探して都合の良いのがあれば検討しますが,それでもないと常時監視中にAI外の移動を検知した(ここが一番ネック)ときに…とかやるの,正直言って無駄骨になりそうですし.
そもそも普通にメイドさんを歩かせていて1ブロックに24体も重なる状況あります?

>持ち物が一杯になったアイテムをシュルカーボックスに入れ

ブロックとして一度置くという方式にすれば,TileEntityが使えるので問題ないのですが,アイテム状態のまま…となるとNBT直操作になるのであまりやりたくないのです.もっともシュルカーボックスの実装は全然見ていないので何とも.
それはそれ,輸送力強化というゲームプレイ上の話ですが,シュルカーボックスに入れるというアイテム整理("収集"ではなく)機能にまで手を出してしまうと少々メイドさんがチート気味になるような気がします.

>長文失礼しますが,そちらから要望を分割希望したい場合はCloseせず返信のみで行って下さい

分割くらいこちらでするんですが,そちらで行っていただけるのであればお願いします.その場合は**2つとも新しいissueを立てていただくようお願いします.**

**Comment by Kohji-Shimazaki** [comment]
承りました.これより新規issueへの分割移動を行います
しばらくそのままでお待ち下さい.

2項目中1項目目を移動しています...

**Comment by Kohji-Shimazaki** [comment]
1項目目が完了しました

2項目中2項目目を移動しています...

**Comment by Kohji-Shimazaki** [comment]
お待たせ致しました.
新規issueへの分割移動が正常に完了しました.
こちらのissueを締め切らせていただきます
ありがとうございました

**Comment by Verclene** [comment]
ご協力ありがとうございます.
議論等は移動先のissueにてお願いします.
