### ISSUE TITLE
初質問

### ISSUE THREAD

**Issue by kuroto5555** [Verclene/LittleMaidReengaged#96]
質問するために登録しました。
リトルメイド１・９．４についての質問です。
メイドを頭に乗せている動画をよく見るので調べてサドルで右クリックすればできると書いてあったのですが、クリエイティブ・サバイバルともにできませんでした。
火薬で赤くなったりなどはしていましたが、頭に乗せることだけ仕様変更なされたのでしょうか？
やり方の変更など見落としがあるのかもしれませんが教えていただけますでしょうか。
以上です

**Comment by Verclene** [comment]
>火薬で赤くなったりなどはしていましたが、頭に乗せることだけ仕様変更なされたのでしょうか？

どこだかで削除しました.修正不可能なバグによるものです.ご了承ください.

**Comment by kuroto5555** [comment]
お早い返事に感謝します、なるほど残念です。回答ありがとうございました！
