### ISSUE TITLE
configのvoice-rate

### ISSUE THREAD

**Issue by jururu** [Verclene/LittleMaidReengaged#97]
configの
#Ratio of playing non-force sound
voiceRate=0.1
の部分は、野良メイドさんだったりヒマなメイドさんだったりが話し始める設定ですよね。
変更しても変わっていないと思うのですが、ここは実装されていますか？
0にしてもおしゃべりしています。

既出・私の勘違いだったらすみません。

**Comment by Verclene** [comment]
現在のところLivingSoundはバニラの再生イベント時に強制的に再生させています.
ほとんど機能していない設定のため,近々ボイス設定をconfigから削除する予定です.

**Comment by jururu** [comment]
承知しました。回答ありがとうございます。
今後の開発を心からお待ちしてます。
